spring.application.name=ecommerce
app.base-url=http://localhost:8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=springstudent
spring.datasource.password=springstudent

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

spring.mvc.hiddenmethod.filter.enabled=true

secret_string=1f33930ad894c3b5aeeaa15848a10caacfa9122b5fa9d3d53b8d0bf3b19514e6c14a23c7e6ead0bc9022da25860a20b8

# --- Email ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=szut.siergiej@gmail.com
spring.mail.password=lvogcghonuigvzvd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

jwt.expiration.ms=86400000
